### ISSUE TITLE
Minor editions

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-ECTA#23]
Title: The capitalization should be done consistently.
p. 1, l. 12: “problems” (plural).
l. 14: Possibly there is not just a single pattern.
p. 2, l. 7: Maybe “not decidable” is better than “impossible to know”.
l. 19f: Training a neural network is not always stochastic. This should be
better specified.
l. 5 from below: “usual” instead of “frequent”.
p. 4, l 24: Move “recently” after “proved”.
p. 5,l. 5 from below: “a memory”.
p. 5, l. 4ff from below: There is something missing in the sentence starting
with “In order”.
p. 6, l. 2: It is not the fitness of the case studies but analyzed in the case
studies.
l. 11: The acronym MADE has not been introduced before.
p. 7, l. 7: “ships are sent”.
p. 8, l. 15: “from a medium”.
l. 22: “where a”.
l. 34: Skip comma.
l. 36: Skip comma.
p. 9, l. 21 from below: “grows to infinity” instead of “is too big”.
p. 10, l. 5: “quite different” instead of “away”.
p. 11: First two sentences are not clear enough.
p. 13, l. 6: “which” instead of “whose”.
p. 14, l. 7: Why don’t you specify the considered stochastic optimization algorithm?
p. 15, 6: Skip “one”.
l. 8: “cases” (plural).
l. 13ff: The statement stating with “At any rate” appears to be too strong and
not well founded by the considered experiments.
l. 19-20: Skip commas.
l. 22: “it is an error” – too strong statement.
p. 18, Ref. 44: Errors with the names?

**Comment by JJ** [comment]
I am leaving today for Brussels and would like to send it this morning. Will you be able to make the changes?

**Comment by fergunet** [comment]
Yes, I can. Starting now. I didn't know the deadline was so close.

El domingo, 21 de febrero de 2016, Juan Julián Merelo Guervós <
notifications@github.com> escribió:

> I am leaving today for Brussels and would like to send it this morning.
> Will you be able to make the changes?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ECTA/issues/23#issuecomment-186775353
> .

## 

Dr. Pablo García Sánchez
University of Granada
http://www.ugr.es/~pablogarcia

**Comment by fergunet** [comment]
Before closing the issue, please @JJ check some issues to solve yet, mainly concerning rewriting stuff that is not clear for the reviewer (but that I would prefer not correct, because probably I will make it worse). My comments are in _italic_
- p. 5, l. 4ff from below: There is something missing in the sentence starting with “In order”.  _I do not know what is missing here_
- p. 11: First two sentences are not clear enough. _In my compiled pdf the sentences (and the ones before and after, just in case) seems clear_
- p. 13, l. 6: “which” instead of “whose”. _"a neural net whose fitness distribution has kurtosis of 15"  seems correct to me_
- l. 13ff: The statement stating with “At any rate” appears to be too strong and not well founded by the considered experiments.
- p. 18, Ref. 44: Errors with the names? _The error was in the @pacastillo paper, so I fixed geneura.bib file, please update it before compiling @JJ_
